name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: main-build
        run: bash ffmpeg_with_srt_auto.sh

      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: ~/bin/ff*
